services:
  app:
    image: imranwebstudio/yasminaarsic-server:latest
    platform: linux/amd64
    container_name: yasminaarsic-server
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://admin:yasminaarsic@db:5432/yasminaarsic-db"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: yasminaarsic-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: yasminaarsic
      POSTGRES_DB: yasminaarsic-db
    volumes:
      - root_pgdata:/var/lib/postgresql

volumes:
  root_pgdata:
