services:
  app:
    image: softvence/yasminaarsic-server:latest
    profiles:
      - prod
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: yasminaarsic-server
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    depends_on:
      - db
    networks:
      - yasminaarsic-network

  db:
    image: postgres:latest
    container_name: yasminaarsic-db
    profiles:
      - prod
      - dev
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: yasminaarsic
      POSTGRES_DB: yasminaarsic-db
    volumes:
      - root_pgdata:/var/lib/postgresql
    networks:
      - yasminaarsic-network

volumes:
  root_pgdata:
networks:
  yasminaarsic-network:
    driver: bridge
